kafka:
  consumers:
    item:
      pollTimeout: 20
      topic: item
      properties:
        bootstrap.servers: localhost:9092
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        reconnect.backoff.ms: 50
        max.poll.records: 5000
        auto.offset.reset: earliest
        group.id: item-consumer
  producers:
    item:
      properties:
        bootstrap.servers: localhost:9092
        schema.registry.url: http://localhost:8081
    order:
      properties:
        bootstrap.servers: localhost:9092
        schema.registry.url: http://localhost:8081
    channels:
      itemChannel: item
      orderChannel: order