/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.smartcat.avro.events.item;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ItemEventType {
  ADD_ITEM, REMOVE_ITEM  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ItemEventType\",\"namespace\":\"io.smartcat.avro.events.item\",\"symbols\":[\"ADD_ITEM\",\"REMOVE_ITEM\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
