/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.smartcat.avro.events.order;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderEventType {
  ADD_ORDER, CLEAR_ORDER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderEventType\",\"namespace\":\"io.smartcat.avro.events.order\",\"symbols\":[\"ADD_ORDER\",\"CLEAR_ORDER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
